name: Deploy CD part

on:
    workflow_run:
        workflows: ["First Test"]
        types:
            - completed

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - name: Install Dependencies
              run: npm ci
            - name: Start API
              run: npm run start