name: DockerHub and Deploy

on:
    push:
        branches: ["main"]

jobs:
    push:
        if: ${{ contains(github.event.head_commit.message, '#docker')}}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_LOGIN }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract Metadata
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: arocode/ugodelire

            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

    pull:
        needs: push
        runs-on: ubuntu-latest

        steps:
            - name: Server Update
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                port: ${{ secrets.PORT }}

                username: ${{ secrets.LOGIN }}
                password: ${{ secrets.PWD }}

                #script: bash update.sh
                script: |
                  docker pull arocode/ugodelire:main
                  docker rm -f marcel
                  docker run -d -p 8888:8888 --name marcel arocode/ugodelire:main

