name: Github Package

on:
    workflow_call

env:
    REGISTRY: ghcr.io
    # Here floriansp40/ugodelire
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Chekout
              uses: actions/checkout@v3

            - name: Registry login ${{ env.REGISTRY }}
              if: github.event_name != 'pull_request'
              uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.ACTIONS_PAT }}

            # Extract metadata (tags, labels) for Docker
            # https://github.com/docker/metadata-action
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                # ghcr.io/Floriansp40/ugodelire
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
                flavor: |
                  latest=true

            # Build and push Docker image with Buildx (don't push on PR)
            # https://github.com/docker/build-push-action
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: ${{ github.event_name != 'pull_request' }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

    compose:
        needs: [build]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 
              uses: actions/checkout@v3
            - name: copy file via ssh password
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.LOGIN }}
                #password: ${{ secrets.PWD }}
                key: ${{ secrets.PRIVATE_KEY }}
                port: ${{ secrets.PORT }}
                source: "./docker-compose.yml"
                target: "."
                
    deploy:
        needs: compose
        runs-on: ubuntu-latest

        steps:
            - id: string
              uses: ASzc/change-string-case-action@v5
              with:
                string: ${{ env.IMAGE_NAME }}
            - name: Docker Compose Up
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                port: ${{ secrets.PORT }}

                username: ${{ secrets.LOGIN }}
                #password: ${{ secrets.PWD }}
                key: ${{ secrets.PRIVATE_KEY }}

                script: |
                  echo ${{ secrets.ACTIONS_PAT }} | docker login ghcr.io -u floriansp40 --password-stdin
                  docker pull ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:latest
                  docker-compose up -d

                # script: |
                #   echo ${{ secrets.ACTIONS_PAT }} | docker login ghcr.io -u floriansp40 --password-stdin
                #   docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                #   docker-compose up -d